# Generated by Django 3.2.9 on 2021-11-29 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ark', '0002_auto_20211129_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_str', models.CharField(max_length=200)),
                ('version_code', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='release',
            name='release_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ark.version'),
        ),
    ]
