# Generated by Django 3.2.9 on 2021-11-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark', '0005_auto_20211130_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='released_at',
        ),
        migrations.AlterField(
            model_name='release',
            name='release_events',
            field=models.ManyToManyField(blank=True, related_name='release_events', to='ark.Event'),
        ),
    ]
