# Generated by Django 3.2.9 on 2021-12-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark', '0006_auto_20211130_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_status',
            field=models.CharField(choices=[('draft', 'draft'), ('pre-release', 'pre-release'), ('released', 'released')], max_length=200),
        ),
    ]
