# Generated by Django 3.2.9 on 2021-12-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark', '0007_alter_release_release_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=200)),
                ('key_data_type', models.CharField(choices=[('Int', 'Int'), ('String', 'String'), ('DateTime', 'DateTime'), ('raw', 'raw')], max_length=200)),
            ],
        ),
    ]
